version: '3.8'
services:
  springboot-app:
    image: amalbkr99/springdata:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://database:3306/springboot
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Amalamira9911
    depends_on:
      - database

  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Amalamira9911
      - MYSQL_DATABASE=springboot

  react-frontend:
    image: amalbkr99/react_container:latest
    ports:
      - "3000:3000"

